services:
  - type: web
    name: pure-apis
    env: static
    buildCommand: null  # No build needed for simple static site
    staticPublishPath: .
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
